spring:
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  flyway:
    enabled: true
    validate-on-migrate: true
    locations: classpath:db/migration
    default-schema: testdb
  main:
    banner-mode: false;



