spring:
  datasource:
    url: jdbc:h2:mem:group_chat;
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    default-schema: group_chat
